version: '3.7'

services:
    app:
        container_name: app
        build: .
        ports:
            - "8000:80"
            - "5173:5173"
        volumes:
            - .:/var/www/html
        environment:
            - VITE_HOST=0.0.0.0
            - VITE_PORT=5173
            - VITE_API_URL=http://localhost:80/api
            - APP_ENV=production
    db:
        container_name: db
        image: mcr.microsoft.com/mssql/server
        environment:
            SA_PASSWORD: "2o24Pass"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
